name: HeliBoard-Auto-Build

on:
  workflow_dispatch: # Allows you to start it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create Temporary Signing Key
        run: |
          keytool -genkey -v -keystore release.keystore -alias helikey -keyalg RSA -keysize 2048 -validity 10000 -storepass password123 -keypass password123 -dname "CN=HeliUser, OU=Dev, O=HeliBoard, L=World, S=World, C=US"

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Sign the APK
        run: |
          # Finds the build-tools and the unsigned APK automatically
          APK_SIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | tail -1)
          UNSIGNED_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          
          # Sign it and rename it
          $APK_SIGNER sign --ks release.keystore --ks-pass pass:password123 --key-pass pass:password123 --out HeliBoard-Signed.apk "$UNSIGNED_APK"

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HeliBoard-Release-Package
          path: HeliBoard-Signed.apk
